### ISSUE TITLE
possibility for dynamic link for id token and refesh token.

### ISSUE THREAD

**Issue by sharmavijay86** [OpenUnison/openunison-k8s-login-github#17]
Hello Marc,
Just checking th possibility if we can get id token and refresh token on the fly as from url. 
So far my testing.
I am doing login and for every time while login i have to copy kubeconfig context file from login portal and then to run it and use it. 
I am checking the possibility of having id token and refresh token url use in kubeconfig file instead of hard mention  in file.
Benefit i am looking is this-
User on first login gets kubeconfig copied from portal and then use it.
Once the user logged out and login back  both the refresh token and  id token config file gets from referenced url.
In sort it will help me, in not to overwrite config file everytime i am doing login and log out, if i am working on multiple cluster contexts at the same time.

**Comment by mlbiam** [comment]
@sharmavijay86 have you looked at the `oulogin` kubectl plugin (https://github.com/TremoloSecurity/kubectl-login)?  It will allow you to login without first going to the portal, will launch a browser for you if needed and will switch contexts.

**Comment by sharmavijay86** [comment]
@mlbiam  Thanks that will solve the issue . (y)
